import { randomUUID } from "node:crypto";
import { mkdir, open, readFile, rename, rm } from "node:fs/promises";
import path from "node:path";

// Where uploaded document files live: the API server's own disk, never the
// database or Supabase Storage. Keys are generated by the server
// (`<owner id>/<random uuid>`), so a client can never name a path.

export interface FileStore {
  put(key: string, bytes: Buffer): Promise<void>;
  /** Null if the file is missing. */
  get(key: string): Promise<Buffer | null>;
  /** Removes the file; missing files are ignored. */
  remove(key: string): Promise<void>;
}

const KEY = /^[0-9a-f-]{36}\/[0-9a-f-]{36}$/;

export const newStorageKey = (ownerId: string) => `${ownerId}/${randomUUID()}`;

/**
 * Files under `root` (DOCUMENTS_DIR), readable only by the server's user.
 * Writes go to a temporary file first and are renamed into place, so a crash
 * never leaves a half-written document behind its record.
 */
export function diskFileStore(root: string): FileStore {
  const resolve = (key: string) => {
    if (!KEY.test(key)) throw new Error(`invalid storage key: ${key}`);
    return path.join(root, key);
  };
  return {
    put: async (key, bytes) => {
      const target = resolve(key);
      await mkdir(path.dirname(target), { recursive: true, mode: 0o700 });
      const temp = `${target}.${randomUUID()}.part`;
      const handle = await open(temp, "wx", 0o600);
      try { await handle.writeFile(bytes); await handle.sync(); } finally { await handle.close(); }
      await rename(temp, target);
    },
    get: async key => readFile(resolve(key)).catch((err: NodeJS.ErrnoException) => { if (err.code === "ENOENT") return null; throw err; }),
    remove: async key => { await rm(resolve(key), { force: true }); },
  };
}

/** In-memory files for tests. */
export function memoryFileStore(): FileStore & { files: Map<string, Buffer> } {
  const files = new Map<string, Buffer>();
  return {
    files,
    put: async (key, bytes) => { files.set(key, Buffer.from(bytes)); },
    get: async key => files.get(key) ?? null,
    remove: async key => { files.delete(key); },
  };
}

/** The directory for document files: DOCUMENTS_DIR, or ./data/documents under the working directory. */
export const documentsDir = (env: NodeJS.ProcessEnv = process.env) => path.resolve(env["DOCUMENTS_DIR"] || "data/documents");
