import { bigint, index, pgEnum, pgTable, text, timestamp, uuid } from "drizzle-orm/pg-core";
import { applicantProfilesTable } from "./applicants";
import { applicationsTable } from "./applications";

// Records of documents applicants upload: identity documents for the identity
// check, and evidence for an application's requirements. The files themselves
// are never stored in the database or in Supabase Storage: they live on the
// API server's own disk (DOCUMENTS_DIR), and this row records where, plus a
// SHA-256 of the content that is checked on every download. Deleting a
// document removes the file and keeps this row, marked deleted, as a record.
// Row-level security is on with no policies (see ./staff.ts).

export const documentPurposeEnum = pgEnum("document_purpose", ["identity", "application"]);

export const documentsTable = pgTable("documents", {
  id: uuid("id").primaryKey().defaultRandom(),
  ownerId: uuid("owner_id").notNull().references(() => applicantProfilesTable.authUserId),
  purpose: documentPurposeEnum("purpose").notNull(),
  /** Set for application evidence: the application and which of its program's requirements the file supports. */
  applicationId: text("application_id").references(() => applicationsTable.id, { onDelete: "set null" }),
  requirement: text("requirement"),
  fileName: text("file_name").notNull(),
  /** Detected from the file's content, not taken from the upload. */
  contentType: text("content_type").notNull(),
  sizeBytes: bigint("size_bytes", { mode: "number" }).notNull(),
  sha256: text("sha256").notNull(),
  /** Path relative to DOCUMENTS_DIR, generated by the server. */
  storageKey: text("storage_key").notNull().unique(),
  uploadedAt: timestamp("uploaded_at", { withTimezone: true }).notNull().defaultNow(),
  deletedAt: timestamp("deleted_at", { withTimezone: true }),
}, t => [index("documents_owner_idx").on(t.ownerId), index("documents_application_idx").on(t.applicationId)]).enableRLS();

export type DocumentRow = typeof documentsTable.$inferSelect;
